version: "3.8"
services:
  postgres:
    image: postgres
    container_name: "res_admin"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=resume_admin
    ports:
      - "5433:5433"